### ISSUE TITLE
File permissions not kept on obfuscated files

### ISSUE THREAD

**Issue by cabloo** [pk-fr/yakpro-po#17]
I ran the obfuscator on a project that has a bin folder with a few executable files but they lost the execution bit. It would be nice if the obfuscator kept the same permissions for the files.

**Comment by pk-fr** [comment]
very good idea,

I just published a new release, the obfuscator will also preserve owner and group for the files...

**Comment by cabloo** [comment]
@pk-fr thanks, that was fast!!

Excellent product by the way, this was the only issue I ran into (besides lack of PHP7 support, I suppose). I expected to spend more time dealing with troubles obfuscating my application because of how big it is.

**Comment by pk-fr** [comment]
@cabloo 
I plan to have php7 support, but I need to upgrade my dev machine first. (both hardware & software)...
and I haven't found yet the hardware that I need...
( passive machine based on AKASA Euler  & i7-6700T, but the only thin mini-itx motherboard with M.2 socket is the ga-h170tn which is not available in France, I asked gigabyte and they answer me to wait for the z200  séries... so I am waiting...)
my current dev machine is an old passive one (already AKASA Euler) with ubuntu 12.04 LTS and php 5.3)

I wrote yakpro-po in order to obfuscate  my own big application wich is a CMS I 'm developping since 2002...

Cheers,
Pascal
