### ISSUE TITLE
functions have different cases

### ISSUE THREAD

**Issue by sercankd** [pk-fr/yakpro-po#21]
![untitled-1](https://cloud.githubusercontent.com/assets/1024476/22618801/dd523a1a-eaee-11e6-8273-b815961daa31.jpg)

This is just one example, all the other functions have different cases & calls.

**Comment by pk-fr** [comment]
Hi Sercan,
Thanks for using yakpro-po ... please star it if you like it...

It is a feature, not a bug! 

[http://php.net/manual/en/functions.user-defined.php](http://php.net/manual/en/functions.user-defined.php )

> Note:  Function names are case-insensitive, though it is usually good form to call functions as they appear in their declaration

yakpro-po modifies case of items that are case insensitive in order to increase obfuscation!

as commented in the source code : 
```
// case-sensitive:      variable names, constant name, array keys, class properties, labels 
// case-insensitive:    function names, class names, class method names, namespaces, keywords and constructs 

```

**Comment by pk-fr** [comment]
I just saw you already stared it ;o)

**Comment by sercankd** [comment]
But its a problem for me, since those two files are connected eachother. One on the left have different case and other trying to call it with different case. It gives errors like function not found etc.

**Comment by pk-fr** [comment]
your problems cannot be related to case ...
try a little code like this to be convinced...:
```
<?php
    function hello() { echo "hello\n";}
    for($i=0;$i<3;++$i) HeLlO();
?>
```
