### ISSUE TITLE
error when requiring another php file

### ISSUE THREAD

**Issue by mostafa2142** [pk-fr/yakpro-po#86]
so i finally managed to install linux mint and i obfuscate my php files successully ,
but the problem is that when i send a http request to my php file (to test if they work with the new obfuscator)
it throws these errors : 
Warning: require(qIbEN): failed to open stream: No such file or directory
Fatal error: require(): Failed opening required 'qIbEN' (include_path='.;C:\php\pear')
Warning: Use of undefined constant qIbEN - assumed 'qIbEN'

so any idea where why im getting these errors ?

**Comment by mostafa2142** [comment]
so i find out that the require(qIbEN): is actually the jwt library files,
then i obfuscated the jwt php files too but i still get the same errors

**Comment by pk-fr** [comment]
yakpro-po has been designed to obfuscate standalone projects only !!!.

if you use external libraries, you have to obfuscate also the libray, and modify it in order to make it run obfuscated...
if your program is a Library/plugin of another Software/Framework,
the you have to modify/port the external Software/Framework source code in order to obfuscate it and have it run obfuscated.
you have also to maintain a specific yakpro-po.cfg whith all things that are not to be obfuscated across each new version of the external Software/Framework

both are to be obfuscated within the same project!
do not obfuscate separately as each token is randomly created and different on different projects!
see:

    YOU MUST BE AWARE OF THE FOLLOWING: in README.md
    See Hints for preparing your Software to be run obfuscated section of README.md
